sys.path.append("/dls/science/groups/i04-1/elliot-dev/Work/exhaustive_search")
from exhaustive.prepare.copyatoms import copy_atoms
from copy_phil import copy_phil

"""
Refine crystals from visits:

mx19301-17 x2074 - x2121
mx19301-18 x2130 -x2154
mx19301-20 x2160 - x2232

using the dimple files generated by running these crystals through XChemExplorer.
Copy atoms from known structure. 

Uses copy_atom function from exhaustive search
"""

pdb = "/dls/science/groups/i04-1/elliot-dev/Work/exhaustive_search_data/" \
      "covalent_ratios_refine/NUDT7A-x1907/refine.pdb"
cif = "/dls/science/groups/i04-1/elliot-dev/Work/exhaustive_search_data/" \
      "covalent_ratios_refine/NUDT7A-x1907/NUDT7A-x1907_LIG_CYS.cif"

copy_params = copy_phil.extract()

copy_params.input.path = "/dls/labxchem/data/2017/lb18145-49/processing/analysis/initial_model"
copy_params.input.prefix = 'NUDT7A-x'
copy_params.input.start_xtal_number = 2160
copy_params.input.end_xtal_number = 2232
copy_params.input.base_pdb = pdb
copy_params.input.atoms_new = [['E','1']]
copy_params.input.cif = cif
copy_params.input.link_record_list =["LINKR        C  CLIG E   1                 SG ACYS A  73                LIG-CYS\n",
                                     "LINKR        D  CLIG E   1                 SG ACYS A  73                LIG-CYS\n"]

copy_params.output.out_dir = "/dls/science/groups/i04-1/elliot-dev/Work/NUDT7A_mass_spec_refinements/copy_atoms"

copy_atoms(copy_params)


